spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sec
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  docker:
    compose:
      lifecycle-management: start_only

server:
  port: 8081
